# Generated by Django 4.2 on 2023-04-20 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatuser",
            name="User",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="accounts.accountuser",
            ),
        ),
    ]
